### PR TITLE
Adding Organization to side bar #115

### PR DESCRIPTION
**Pull request by aashreya**

### CODE REVIEW

**Comment by aashreya** [comment]
@tommysullivan / @PatrickMetsch The side bar with organization is complete. On click it all navigates to the home page for now. These changes can be merged or continued in the same branch.

**Comment by tommysullivan** [comment]
@aashreya just fyi couple new capabilities:

`hp createIssueAndBranch "issue description in quotes"`

This will create a new github issue with description on github.com, create a local branch name containing the issue name and an abbreviated description with dashes in it, then check out that branch.

`hp addCommitPushAndPullRequest`

This will do a `git add -A` then `git commit -m "the description you used when creating the issue appears here automatically"` then pushes to the remote branch, and generates a new pull request also with the same description, outputting the URL of the newly created pull request to the screen.

`hp hub pr checkout 116`

This command allows me to check out and locally run your PR (and reminds me if i have uncommitted changes first). I am adding a new one `hp checkoutPullRequest` which does the same thing but which is more discoverable since it is in the list of help commands outputted when running `./hp`

cool man!

**Comment by tommysullivan** [comment]
one can also do `hp branch [githubIssueId]` to create the properly named branch for an already existing github issue

**Comment by tommysullivan** [comment]
looks good dude!

**Pull request merged**
